### ISSUE TITLE
 ERROR The requested URL could not be retrieved when trying to open http://hello-kubecon:8000

### ISSUE THREAD

**Issue by lhoupert** [antongisli/maas-baremetal-k8s-tutorial#4]
Finally, I tried again to remove and deploy hello-kubecon  with `--config juju-external-hostname=kubecon.test` and it worked.

However both way of deploying  `hello-kubecon`  leads to this error:

![image](https://user-images.githubusercontent.com/10154151/158430283-90e4e646-ab34-48b8-8a3d-55a011b7d66a.png)

I don't think I missed anything in the set up:

``` 
❯ kubectl get ingress -n hello-kubecon
NAME                    CLASS                      HOSTS           ADDRESS       PORTS   AGE
hello-kubecon-ingress   nginx-ingress-controller   hello-kubecon   10.10.10.21   80      6m12s
```

```
 sudo iptables -t nat -v -L -n --line-number
Chain PREROUTING (policy ACCEPT 1733 packets, 143K bytes)
num   pkts bytes target     prot opt in     out     source               destination
1    21537 1301K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
2       28  1456 DNAT       tcp  --  eno1   *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8000 to:10.10.10.21:80

Chain INPUT (policy ACCEPT 376 packets, 41543 bytes)
num   pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 3731 packets, 289K bytes)
num   pkts bytes target     prot opt in     out     source               destination
1     3618  217K DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 5953 packets, 392K bytes)
num   pkts bytes target     prot opt in     out     source               destination
1     2062  124K MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0
2     4578  404K SNAT       all  --  *      eno1    0.0.0.0/0            0.0.0.0/0            to:192.168.1.166
3        0     0 MASQUERADE  tcp  --  *      *       172.17.0.2           172.17.0.2           tcp dpt:61209
4        0     0 MASQUERADE  tcp  --  *      *       172.17.0.2           172.17.0.2           tcp dpt:61208

```

````
❯ more /etc/hosts
127.0.0.1       localhost
127.0.1.1      B550-AORUS-ELITE-AX-V2

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

192.168.1.166 hello-kubecon
````

Anything I am missing?

**Comment by antongisli** [comment]
Can you telnet to 192.168.1.166:8000 and get a connection? You should at least get a connection to the nginx ingress if everything is working correctly. 

Can you ping 192.168.1.166?

**Comment by lhoupert** [comment]
Yes I could telnet and ping the host. I will give you an update once I manage to get the cluster back online 😅 . It is not an easy thing :-p

Particularly I had two main problems, if we can resolve them, maybe we could add them in the readme?  

1) After rebooting the host server, it happens that I encounter the error:  `No block devices detected using current configuration` on one or several `ceph-osd` units. The error seems related to pre-existing data on the disks, see `Storage device` section on the charmhub page (https://charmhub.io/ceph-osd)
> The charm will go into a blocked state (visible in juju status output) if it detects pre-existing data on a device. In this case the operator can either instruct the charm to ignore the disk (action blacklist-add-disk) or to have it purge all data on the disk (action zap-disk).

How would you purge the disks in the context of your tutorial? What would be the commands to run if you have to do that after line 128?

2) Or the connectivity to one of the MAAS VM can be broken (I open a post on it [here](https://discourse.maas.io/t/problem-of-ssh-connection-to-maas-vm-permission-denied-on-rescue-mode/5862) ) 

An "easy" solution would be to remove juju component and wipe all the MAAS VMs and restart from the beginning but it's not really satisfying.

**Comment by antongisli** [comment]
Yes, I did not do things like keeping the cluster up for long, I blew it away and rebuilt many times. For 1) it sounds like a charm thing, and you could seek help from the charm authors themselves. I won't be able to investigate that.
For 2) I'm actually not sure. It seems like the ssh keys are not there in rescue mode (?). Also why the  machine is down I don't know, did you see if it had power turned on in MAAS?

**Comment by lhoupert** [comment]
Thank you Anton. For 1), where is the best place to ask for help ? 
I don't want to overload the Juju discourse.

For 2), yes it is turned on.
![image](https://user-images.githubusercontent.com/10154151/158634672-39989173-6b49-49ca-8349-5fab9c7d4734.png)

I will wait a couple of days to see if someone has an answer and otherwise I will just start again from scratch.  Thanks for the help.

**Comment by antongisli** [comment]
The juju team and other charmers would likely LOVE to hear from you on their discourse! Don't hesitate! They want more discussion around these things.
